version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
      - ./www/:/var/www/html:rw
    networks:
      - net-php

  php:
    build: php/php7/
    expose:
      - "9000"
    volumes:
      - ./conf/php/php.ini:/etc/php7/php.ini:ro
      - ./conf/php/php-fpm.conf:/etc/php7/php-fpm.conf:ro
      - ./log/php/:/var/log/php7/:rw
      - ./www/:/var/www/html:rw
    networks:
      - net-php
      - net-mysql

  mysql:
    image: mysql:5.7
    container_name: my-mysql
    ports:
    - "3306:3306"
    volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./log/mysql/:/var/log/mysql/:rw
    - ./mysql/:/var/lib/mysql/:rw
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
    - net-mysql

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
    - "6379:6379"
    networks:
    - net-php

networks:
  net-php:
    driver: bridge
  net-mysql:
    driver: bridgeb